In [3]:
# Problema 3. Parte 1

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sci
import sympy as sp

sp.init_printing()

def MinusDim(R):
    c=3
    R_new=np.zeros((c,c))
    
    for j in range(c):
        for i in range(c):
            R_new[i,j]=R[i,j]
            
    return R_new

#Bx=d

epsi=10**(-12)

B=np.matrix([[1,1,1],
  [epsi,0,0],
  [0,epsi,0],
  [0,0,epsi]])

d=np.matrix([[3],[3*epsi],[-epsi],[epsi]])

#--------------------------------------------------------------

# 3.1.1

q,r = sci.qr(B)

#---------------------------------------------------------------

# 3.1.2

#x=B/d

R2=MinusDim(r)

q_inv=np.linalg.inv(q)
d_2=q_inv.dot(d)

d2=np.zeros((3,1))

for i in range(3):
    d2[i,0]=d_2[i,0]

x=np.linalg.inv(R2).dot(d2)
sol=R2.dot(x)-d2
sol=sp.Matrix(sol)

q=sp.Matrix(q)
r=sp.Matrix(r)

q.evalf(5)

⎡  -1.0    7.0711e-13  4.0825e-13  -5.7735e-13⎤
⎢                                             ⎥
⎢-1.0e-12   -0.70711    -0.40825     0.57735  ⎥
⎢                                             ⎥
⎢   0       0.70711     -0.40825     0.57735  ⎥
⎢                                             ⎥
⎣   0          0         0.8165      0.57735  ⎦

In [7]:
# Problema 3. Parte 2. Cálculos explícitos

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sci
import math
import sympy as sp

sp.init_printing()
#Bx=d

epsi=10**(-12)

B=np.array([[1,1,1],
  [epsi,0,0],
  [0,epsi,0],
  [0,0,epsi]])

d=np.array([3,3*epsi,-epsi,epsi])

# v1------------------------------------------

x1=np.zeros((4,1))

for i in range(4):
    x1[i,0]=B[i,0]

norm_x1=np.linalg.norm(x1)

e1_1=np.zeros((4,1))
e1_1[0,0]=1

sign_1=math.copysign(1,norm_x1)
    
v1=-1*sign_1*norm_x1*e1_1-x1

v1=sp.Matrix(v1)

    
v1v1T=np.dot(v1,v1.T)

v1Tv1=np.dot(v1.T,v1)

I=np.eye(4)

H1=I-2*v1v1T/v1Tv1

L1=H1.dot(B)

# v2------------------------------------------

x2=np.zeros((3,1))

for i in range(3):
    x2[i,0]=L1[i+1,1]
    
norm_x2=np.linalg.norm(x2)

e1_2=np.zeros((3,1))
e1_2[0,0]=1

sign_2=math.copysign(1,norm_x1)
    
v2=-1*sign_2*norm_x2*e1_2-x2

    
v2v2T=np.dot(v2,v2.T)

v2Tv2=np.dot(v2.T,v2)

I=np.eye(3)

H2prime=I-2*v2v2T/v2Tv2

H2=np.eye(4)

for i in range(1,4):
    for j in range(1,4):
        H2[i,j]=H2prime[i-1,j-1]

L2=H2.dot(L1)

# v3------------------------------------------

x3=np.zeros((2,1))

for i in range(2):
    x3[i,0]=L2[i+2,2]
    
norm_x3=np.linalg.norm(x3)

e1_3=np.zeros((2,1))
e1_3[0,0]=1

sign_3=math.copysign(1,norm_x3)
    
v3=-1*sign_3*norm_x3*e1_3-x3

    
v3v3T=np.dot(v3,v3.T)

v3Tv3=np.dot(v3.T,v3)

I=np.eye(2)

H3prime=I-2*v3v3T/v3Tv3

H3=np.eye(4)

for i in range(2,4):
    for j in range(2,4):
        H3[i,j]=H3prime[i-2,j-2]
        
R=H3.dot(H2.dot(H1.dot(B)))
Q=H1.dot(H2.dot(H3))
B_test=Q.dot(R)
R=sp.Matrix(R)
Q=sp.Matrix(Q)
B_test=sp.Matrix(B_test)

Q.evalf(5)

⎡  -1.0    -7.0711e-13  -4.0825e-13  -5.7735e-13⎤
⎢                                               ⎥
⎢-1.0e-12    0.70711      0.40825      0.57735  ⎥
⎢                                               ⎥
⎢   0       -0.70711      0.40825      0.57735  ⎥
⎢                                               ⎥
⎣   0           0         -0.8165      0.57735  ⎦

In [8]:
# Problema 3. Parte 3. Optimización

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sci
import math

#Bx=d

epsi=10**(-12)

B=np.array([[1,1,1],
  [epsi,0,0],
  [0,epsi,0],
  [0,0,epsi]])

d=np.array([3,3*epsi,-epsi,epsi])

c=np.size(B,1)
f=np.size(B,0)

H=np.zeros((f,f,c))
R=B
L=B
for i in range(c):
    l=f-i
    
    e=np.zeros((l,1))
    e[0,0]=1
    
    x=np.zeros((l,1))
    
    for j in range(l):
        x[j,0]=L[j+i,i]
        
    norm_x=np.linalg.norm(x)
    sign=math.copysign(1,norm_x)
    
    v=-1*sign*norm_x*e-x
    vvT=np.dot(v,v.T)
    vTv=np.dot(v.T,v)
    I=np.eye(l)
    H_prime=I-2*vvT/vTv
    
    if i==0:
        H[:,:,i]=H_prime
    if i>0:
        H[:,:,i]=np.eye(f)
        for k in range(i,4):
            for j in range(i,4):
                H[k,j,i]=H_prime[k-i,j-i]
    
    L=H[:,:,i].dot(L)
                
    R=H[:,:,i].dot(R) 
    
Q=np.eye(f)

for i in range(c-1,-1,-1):
    Q=H[:,:,i].dot(Q)
    
B_test=Q.dot(R)

print('Q')
print(Q)
print('R')
print(R)
print('QR')
print(B_test)

Q
[[-1.00000000e+00 -7.07106781e-13 -4.08248290e-13 -5.77350269e-13]
 [-1.00000000e-12  7.07106781e-01  4.08248290e-01  5.77350269e-01]
 [ 0.00000000e+00 -7.07106781e-01  4.08248290e-01  5.77350269e-01]
 [ 0.00000000e+00  0.00000000e+00 -8.16496581e-01  5.77350269e-01]]
R
[[-1.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00 -1.41421356e-12 -7.07106781e-13]
 [ 0.00000000e+00  1.16594958e-28 -1.22474487e-12]
 [ 0.00000000e+00  1.64890171e-28  0.00000000e+00]]
QR
[[ 1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e-12 -4.03896783e-28 -1.00974196e-28]
 [ 0.00000000e+00  1.00000000e-12  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e-12]]


In [9]:
# Problema 3. Parte 4. Cálculo final

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sci
import math

def MinusDim(R):
    c=np.size(R,1)
    R_new=np.zeros((c,c))
    
    for j in range(c):
        for i in range(c):
            R_new[i,j]=R[i,j]
            
    return R_new

#Bx=d

epsi=10**(-12)

B=np.array([[1,1,1],
  [epsi,0,0],
  [0,epsi,0],
  [0,0,epsi]])

d=np.array([[3],[3*epsi],[-epsi],[epsi]])

c=np.size(B,1)
f=np.size(B,0)

H=np.zeros((f,f,c))
R=B
L=B
for i in range(c):
    l=f-i
    
    e=np.zeros((l,1))
    e[0,0]=1
    
    x=np.zeros((l,1))
    
    for j in range(l):
        x[j,0]=L[j+i,i]
        
    norm_x=np.linalg.norm(x)
    sign=math.copysign(1,norm_x)
    
    v=-1*sign*norm_x*e-x
    vvT=np.dot(v,v.T)
    vTv=np.dot(v.T,v)
    I=np.eye(l)
    H_prime=I-2*vvT/vTv
    
    if i==0:
        H[:,:,i]=H_prime
    if i>0:
        H[:,:,i]=np.eye(f)
        for k in range(i,4):
            for j in range(i,4):
                H[k,j,i]=H_prime[k-i,j-i]
    
    L=H[:,:,i].dot(L)
    R=H[:,:,i].dot(R)
    d=H[:,:,i].dot(d)
    


R2=MinusDim(R)
m=np.size(R,1)
d2=np.zeros((m,1))

for i in range(m):
    d2[i,0]=d[i,0]

x=sci.solve(R2,d2)
x=sp.Matrix(x)
d2=sp.Matrix(d2)
R2=sp.Matrix(R2)

O=R2*x-d2
mincua=O.norm(2)
mincua